environments:
  bare_metal_pypi_package:
    environment_variables:
      PYPI_USERNAME: '{{SECRET:[pypi][gen-vm-image][username]}}'
      PYPI_PASSWORD: '{{SECRET:[pypi][gen-vm-image][username]}}'
    pipelines:
    - bare_metal_pypi_package
format_version: 10
pipelines:
  bare_metal_pypi_package:
    display_order: -1
    group: bare_metal_pypi_package
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      ucphhpc_images:
        branch: main
        destination: gen-vm-image
        git: https://github.com/ucphhpc/gen-vm-image.git
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_GEN_VM_IMAGE
      DEFAULT_TAG: 0.0.0a1
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: gen-vm-image
      TEST_DIRECTORY: gen-vm-image
    template: bare_metal_pypi_package
