environments:
  bare_metal_vm_image:
    environment_variables:
      GIT_USER: '{{SECRET:[github][username]}}'
    pipelines:
    - saga-base
format_version: 10
pipelines:
  saga-base:
    display_order: -1
    group: bare_metal_vm_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      ucphhpc_images:
        branch: main
        destination: gen-vm-image
        git: https://github.com/ucphhpc/gen-vm-image.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_SIF_VM_IMAGES
      DEFAULT_TAG: 9.3
      IMAGE: Rocky
      IMAGE_PIPELINE: saga-base
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: gen-vm-image
      TEST_DIRECTORY: gen-vm-image
    template: bare_metal_vm_image
